name:                dicta
version:             0.1.0.0
github:              "vilu/dicta"
license:             BSD3
author:              "Viktor Lund"
maintainer:          "lund.viktor@gmail.com"
copyright:           "2018 Viktor Lund"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vilu/dicta#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - containers
    - mtl
    - lens

tests:
  dicta-test:
    main:                Test.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dicta
    - tasty
    - tasty-hspec
